// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Company struct {
	ID          pgtype.UUID
	OwnerUserID pgtype.UUID
	Name        string
	Description pgtype.Text
	IsVerified  bool
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type ResourceRequest struct {
	ID           pgtype.UUID
	CompanyID    pgtype.UUID
	ResourceType string
	Description  pgtype.Text
	Status       string
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}
